### ISSUE TITLE
Tranfer Learning On Entire Network without Model Define

### ISSUE THREAD

**Issue by hshwang88** [kerry-Cho/transfer-learning-Libtorch#4]
안녕하세요. Libtorch 사용 중 많은 도움이 되고 있습니다.
다름이 아니라 Torchscript 모델을 Libtorch상에서 load하고 training 수행 시
네트워크를 모델을 다시 정의하지 않고 Torchscript 모델만 가지고 전체 네트워크 학습이 가능한 방법인지 여쭈고자 합니다.
즉 Resnet 구조체를 정의하지 않고도 전체 네트워크 training resume이 가능한지를 알고 싶습니다.

감사합니다.

**Comment by Kerry-Cho** [comment]
네 안녕하세요. 도움이 된다고 하니 고맙습니다.
일단 이 레포지토리는  Torchscript 의 모델은 Loading 해서 학습이 가능하게 끔 구현 되어 있습니다.
1.7 버전까지 pytorch Vision의 Pretrained 모델 데이터를 활용 할 수 있게 끔 구현 되어 있습니다. 

적어도 1.7 버전까지는 말씀 하신 내용은 TorchScript만으로는 불가능 합니다. 

아래 코드의 경우 공식 예제 인데 254 라인 부터 259 라인까지보면 네트워크를 재구성 합니다. 
Torchscript를 사용 하면 모델 파일을 2개로 관리 셔야 할 수도 있습니다.
https://github.com/pytorch/examples/blob/00ea159a99f5cb3f3301a9bf0baa1a5089c7e217/cpp/transfer-learning/main.cpp#L254

추가로 네트워크 구조만 동일 하게 구성 하시면 Libtoch와 PyTorch Model 간 데이터 복사는 이상 없이 가능 합니다.

**Comment by Kerry-Cho** [comment]
https://github.com/kerry-Cho/transfer-learning-Libtorch/blob/master/Model/convert.py

**Comment by Kerry-Cho** [comment]
@hshwang88 Libtorch maintainer 애가 얘기 하길 TorchScript로 Export된 모델은 Gradient를 추척 하지 않는 다네요.  1.10 버전은 어떻게 됬나 모르겠네요. 구조상 불 가능해요.

**Comment by hshwang88** [comment]
@kerry-Cho 아하, 그렇군요. 혹시 해당 LibTorch maintainer 분의 답변이 공개되어 있다면 링크 공유 부탁 드려도 괜찮을까요?

**Comment by Kerry-Cho** [comment]
PyTorch 개발자 답변입니다. 미팅 하고 와서 답변이 늦었네요. 
19년도 기준이니까 현재는 어떻게 개발 되어 가고 있는지 모르겠네요.
하시려고 하는 모델이 뭔가요? 
@hshwang88  https://discuss.pytorch.org/t/how-to-save-torchscript-model-using-cpp/59743/10?u=21fa417e3fb06e56040c

**Comment by hshwang88** [comment]
링크 감사합니다. 모델 자체는 단순히 기존의 torchvision vggnet이나 resnet 모델인데,
프로젝트의 목적은 LibTorch상에서 추가로 모델 선언을 일일이 코딩하는 소요를 줄이기 위해
이미 Pytorch상에서 성능이 검증된 torchscript 모델만 가지고
네트워크 학습이랑 추론이 모두 가능하게 하는 것이 목적이라서 그렇습니다.

관련된 내용을 좀 찾아보니 torchscript model에서 weights를 vector로 변환해서 optimizer 학습 parameter로 하면 학습이 가능한것 같네요.
https://github.com/pytorch/pytorch/issues/28478#issuecomment-610897844

**Comment by Kerry-Cho** [comment]
말씀 하신 내용 정도라면 굳이 모델을 재 선언 하실 필요가 없을듯 하네요.
아래 링크를 참조 하시면 될 것같습니다. 아래 코드에 이미 대중적인 모델들의 경우 다 만들어져있고 검증 되어 있습니다.
제 코드를 조금 수정 해서 학습 하는 것도 어렵지 않습니다. 
https://github.com/pytorch/vision/tree/main/torchvision/csrc/models

detecting 모델의 경우 https://github.com/facebookresearch/detr 코드를 C++로 쉽게 변환 할 수 있어 보입니다.

**Comment by Kerry-Cho** [comment]
원래 안됬었는데 해결 됬나보네요 ^^ @hshwang88  도움 필요 하면 또 얘기 하세요.
